### PR TITLE
fix: upgrade all dependencies

### PR DESCRIPTION
**Pull request by patrickmichalina**
`"meriyah": "4.0.0"` is the big one that should fix an issue I am having.

### CODE REVIEW

**Review by vegarringdal — APPROVED** [review]
👍 
I dont have any problems with this.

**Comment by charsleysa** [comment]
@patrickmichalina the version restrictions mean that patch versions cannot be used, would it not be better to use `^4.0.0` instead? or even `~4.0.0`? Same for chokidar

**Comment by patrickmichalina** [comment]
Yeah good point I was just copying the previous format. Can change it though

**Comment by nchanged** [comment]
@patrickmichalina is it good to merge?

**Comment by patrickmichalina** [comment]
@nchanged yeah. I updated the resolutions as recommended by @charsleysa

**Pull request merged**
