### PR TITLE
feat: expose `package.json` in file info

### PR DESCRIPTION
**Pull request by calebboyd**
This sets the raw `package.json` data onto a `packageJson` property in `IPackageInformation`

Also gets the sass dep extraction tests working on windows.

The test for the `packageJson` property is a bit hacky, mostly because there is no way (afaik) to configure a PathMaster instance outside of the global Config object

### CODE REVIEW

**Comment by nchanged** [comment]
Do you really think we need to carry `package.json` data everywhere?

**Comment by calebboyd** [comment]
I figured its useful contextual information for a file. Its just a json object. If you don't to merge it thats fine. I suppose the plugin could just pull it from the nearest node_modules folder of an "entryFile"...

I've removed it -- still have the other things in though if you want to merge them.

**Comment by nchanged** [comment]
i was just thinking, since it's in memory already it can be in the object, I think it's fine.
Btw it won't be available in every file, just the entry point.

**Comment by calebboyd** [comment]
Ahh, I was thinking I needed to identify each module to find the native modules... but I think it can just inspect the dependencies as they become available.

**Pull request merged**
