### PR TITLE
fix windows cache race condition (Fixes #383)

### LINKED ISSUE #383: Stuck at start - Error: ENOTEMPTY: directory not empty, rmdir
Win8.1 x64
`-- fuse-box@1.3.126`
```
Error: ENOTEMPTY: directory not empty, rmdir 'D:\My\Dev\angular-fusebox-seed\.fusebox\cache\1.3.126\D%3A%5CMy%5CDev%5Cangular-fusebox-seedD%3A%5CMy%5CDev%5Cangular-fusebox-seed%5Cbuild%5Capp.js'
    at Object.fs.rmdirSync (fs.js:819:18)
    at rmkidsSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:300:11)
    at rmdirSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:289:7)
    at rimrafSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:254:7)
    at D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:298:5
    at Array.forEach (native)
    at rmkidsSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:297:26)
    at rmdirSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:289:7)
    at rimrafSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:254:7)
    at D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:298:5
    at Array.forEach (native)
    at rmkidsSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:297:26)
    at rmdirSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:289:7)
    at rimrafSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:254:7)
    at D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:298:5
    at Array.forEach (native)
    at rmkidsSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:297:26)
    at rmdirSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:289:7)
    at Function.rimrafSync [as sync] (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\rimraf.js:254:7)
    at Object.removeSync (D:\My\Dev\angular-fusebox-seed\node_modules\fs-extra\lib\remove\index.js:4:17)
    at Object.removeFolder (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\Utils.js:83:13)
    at WorkFlowContext.nukeCache (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\core\WorkflowContext.js:83:17)
    at FuseBox.compareConfig (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\core\FuseBox.js:177:34)
    at new FuseBox (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\core\FuseBox.js:138:14)
    at Function.init (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\core\FuseBox.js:141:16)
    at realm_utils_1.each (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\core\FuseBox.js:163:36)
    at iterate (D:\My\Dev\angular-fusebox-seed\node_modules\realm-utils\dist\commonjs\each.js:79:34)
    at D:\My\Dev\angular-fusebox-seed\node_modules\realm-utils\dist\commonjs\each.js:92:16
    at Object.exports.Each [as each] (D:\My\Dev\angular-fusebox-seed\node_modules\realm-utils\dist\commonjs\each.js:9:12)
    at FuseBox.bundle (D:\My\Dev\angular-fusebox-seed\node_modules\fuse-box\dist\commonjs\core\FuseBox.js:161:34)
    at D:\My\Dev\angular-fusebox-seed\gulpfile.ts:100:32
    at taskWrapper (D:\My\Dev\angular-fusebox-seed\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (D:\My\Dev\angular-fusebox-seed\node_modules\async-done\index.js:36:18)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```
I suppose this is some kind of 'smart' cache is trying to delete cache folder with no luck.
Please provide option to disable it (cache deleting)

Issue is not reproduced when settings is `cache: false`

### PR DESCRIPTION
**Pull request by unlight**

### CODE REVIEW

**Comment by aretecode** [comment]
this may have drastic speed implications :/

**Comment by unlight** [comment]
Why? Because it `*Sync` function? I disagree.
1. This may not because
 * it happens once at start only (if I not mistake)
 * it is console app with single user, and block event loop is acceptable in this case
2. FuseBox use sync functions a lot [see](https://github.com/fuse-box/fuse-box/search?utf8=%E2%9C%93&q=readFileSync)

**Comment by nchanged** [comment]
@unlight the last file to write is the heaviest. It may take a long time to write it.

**Comment by unlight** [comment]
@nchanged
For me `mainStr` is:
```
#!/usr/bin/env node

require('gulp-cli')();
```
I suppose it is unexpected, but is another story :)

Default buffer is 64Kb, I do not think that's config will be so big.
Anyway it is better than:
```
fs.writeFile(configPath, mainStr, () => { });
```
1. Error swallowed
2. This happens before nukeCache (Window at this moment create file descriptor (file with empty content appears) and and prevent deleting directory)

**Comment by nchanged** [comment]
Cache nuking happens only for the target folder. So it does not nuke everything.

**Comment by nchanged** [comment]
And btw, https://github.com/fuse-box/fuse-box/issues/403

**Comment by devmondo** [comment]
#407

**Pull request closed without merging**
