### PR TITLE
chore: update all dep

### PR DESCRIPTION
**Pull request by vegarringdal**
image

@patrickmichalina, figured I could help you :-)
dont know if we break anything..

### CODE REVIEW

**Comment by vegarringdal** [comment]
I have no idea if I have broken something 😂 
But got it atleast to pass test now 😄

**Review by charsleysa — APPROVED** [review]
LGTM

**Review by patrickmichalina — APPROVED** [review]
awesome

**Comment by vegarringdal** [comment]
@nchanged 
Did I break any scripts etc with this update ?

**Review by nchanged — APPROVED** [review]
👍 thanks!

**Pull request merged**
