### PR TITLE
Fix RegExp test subject for plugins to apply

### PR DESCRIPTION
**Pull request by indrimuska**
Replaced full path in favor of relative path (from `homeDir`).
Ref. #270

### CODE REVIEW

**Comment by nchanged** [comment]
I did not get, what is it exactly you have solved here?

**Comment by indrimuska** [comment]
Check out problem and solution in #270

**Comment by nchanged** [comment]
Brilliant!!! Could you be so kind and write a few test cases?

**Comment by indrimuska** [comment]
I don't think of being able to.

**Comment by nchanged** [comment]
No worries man! Thanks a lot!

**Pull request merged**
