### PR TITLE
chore: Added doc about transformerAtPath

### PR DESCRIPTION
**Pull request by FKobus**
Based on after merge comments in: https://github.com/fuse-box/fuse-box/pull/1707

### CODE REVIEW

**Comment by FKobus** [comment]
I think we should create a format for it, because as I wrote, there are multiple ways to invoke it. Maybe good to choose a pattern and enforce that to plugins that use the transformerAtPath

**Comment by nchanged** [comment]
@FKobus I think it depends on what user needs. Maybe a plugin will use a transformer and some internal module operations....It could be both.

**Comment by SephReed** [comment]
From what I know of transformers, I think a hook pattern would be really solid.  I'm hazily imagining something like this:

```
type StandardizedTransformer = Mystery;

interface ITranformerHooks {
  before: {
    all: StandardizedTransformer,
    compile: StandardizedTransformer,
    treeShake: StandardizedTransformer,
    bundler:  StandardizedTransformer,
  },
  after: {
    all: StandardizedTransformer,
    compile: StandardizedTransformer,
    treeShake: StandardizedTransformer,
    bundler:  StandardizedTransformer,
  },
}

transformerThing.addHook({
  before: {
    all: {
     priority: 10,
     fn: (ctx) => doFoo(ctx)
    }
  }
});

transformerThing.addHook({
  before: {
    all: {
     priority: 3.4,
     fn: (ctx) => doBar(ctx)
    }
  }
});
```

This is totally not thought out, more just to show hook pattern.

I've seen this pattern in feathersjs (https://docs.feathersjs.com/guides/basics/hooks.html) and it works really, really well for adding arbitrary transformations to data at arbitrary points.  Very easy to read and understand.

**Comment by nchanged** [comment]
@SephReed It actually makes a lot of sense. I am working on production transformers, and I've realised that I missing those hooks. There are multiple stages. So instead of creating multiple transformers it would make sense to have those handlers.

**Pull request merged**
