### PR TITLE
proposal: tslint configuration

### PR DESCRIPTION
**Pull request by CzBuCHi**
Im proposing to clean up whole codebase by adding TSLint into the mix. That means fixing more than 6000 lint errors all over the place....

- list of all TSLint errors: [TSLINT_ERRORS.md](https://raw.githubusercontent.com/CzBuCHi/fuse-box/7a8da0877873f164f03fda6183772eec46b6dbdd/TSLINT_ERRORS.md)
- list of all broken rules: [tslint.json](https://raw.githubusercontent.com/CzBuCHi/fuse-box/7a8da0877873f164f03fda6183772eec46b6dbdd/src/tslint.json) (with this config no errors occur)

I will create PR for this, but first i need *correct* `tslint.json` and also 👍 from other contributtors ...

Also i would add "object-literal-sort-keys" for interfaces too ([currently not supported by TSLint](https://github.com/palantir/tslint/issues/3482))

PS: Add **discussion tag** to this ...

### CODE REVIEW

**Comment by nchanged** [comment]
@CzBuCHi good idea, I think we need to integrate it into `gulp.js`

And we shouldn't modify a huge amount of files at once, as it will be hard to review

**Comment by CzBuCHi** [comment]
> I think we need to integrate it into gulpfile

i think, that using package.json `precommit` script would be better - it will be called before each commit automatically and its only this code: `"precommit": "tslint --project ./src"` :)

> hard to review

simplest way would be to create commit for each tslint rule ... althrought that would generate 60 of them :)

---

Still i **need TSLint configuratinon** - i personally use this one but i dont wanna force my code style in here ...

{
  "extends": [
    "[tslint:latest](https://github.com/palantir/tslint/blob/master/src/configs/latest.ts)",
    "[tslint-react](https://github.com/palantir/tslint-react)",
    "[tslint-eslint-rules](https://github.com/buzinas/tslint-eslint-rules)",
    "[tslint-immutable](https://github.com/jonaskello/tslint-immutable)",
    "[tslint-clean-code](https://github.com/Glavin001/tslint-clean-code)"
  ],
  "rules": {
    "[arrow-parens](https://palantir.github.io/tslint/rules/arrow-parens/)": [true, "ban-single-arg-parens"],
    "[interface-name](https://palantir.github.io/tslint/rules/interface-name/)": false,
    "[max-classes-per-file](https://palantir.github.io/tslint/rules/max-classes-per-file/)": false,    
    "[max-line-length](https://palantir.github.io/tslint/rules/max-line-length/)": [true, 80],
    "[member-access](https://palantir.github.io/tslint/rules/member-access/)": [true, "no-public"],
    "[no-console](https://palantir.github.io/tslint/rules/no-console/)": false,
    "[quotemark](https://palantir.github.io/tslint/rules/quotemark/)": [true, "single", "jsx-double"],
    "[semicolon](https://palantir.github.io/tslint/rules/semicolon/)": [true, "always", "ignore-bound-class-methods"],
    "[variable-name](https://palantir.github.io/tslint/rules/variable-name/)": [ true, "ban-keywords", "check-format", "allow-leading-underscore", "allow-pascal-case"]
  }
}
}

**Comment by nchanged** [comment]
@CzBuCHi not a big fan of single quotes tho

**Comment by CzBuCHi** [comment]
thats why im posting this here to get some agreement on tslint configuration before any commits ...

**Comment by CzBuCHi** [comment]
ok ... fixing one rule at the time is paint in the ... read end .... fixed all errors in 8 files (that seems reasonable for review)

**Comment by nchanged** [comment]
I don’t like public methods removed

**Comment by nchanged** [comment]
Can this PR be only about adding `tslint.json` ?

**Comment by CzBuCHi** [comment]
> Can this PR be only about adding tslint.json ?

not sure how to revert fork .... creating new one ....

**Pull request closed without merging**
