### PR TITLE
Update WebIndexPlugin to preload multiple types.

### PR DESCRIPTION
**Pull request by JohnPittman**
This gives the ability to preload multiple tag types and override duplicate injections.

I was one of the original people to request the ability to automate preloading resources within the index.html via link tags. I noticed that y'all implemented it for script files but the request was for CSS files so I decided to take a stab at adding it in for you. I did this within the raw editor on github so nothing has been tested but it should work and give you a sense of what it should be. 

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by nchanged** [comment]
@JohnPittman thanks,
Can you give me some use cases and/or examples on how to use it?

**Comment by JohnPittman** [comment]
I really only care about the link tags getting preloaded to not block script tags from getting loaded so the simplest example is that I would want my base styles.css file preloaded. 

Say I expect:  <link rel="preload" href="style.css" as="style">

Plugin config:

WebIndexPlugin({
            appendBundles: true,
            pre: {
                relType: 'load',
                tagTypes: ['style']
            },
            target: 'index.html',
            template: 'src/templates/index.html',
            title: 'React Example'
        }),

**Comment by JohnPittman** [comment]
Personally I think you would be better off controlling each type individually via 'appendBundles' : { preload: true } and add 'appendCSS' etc. instead of relying on the inject option from the CSSPlugin.

**Comment by nchanged** [comment]
Right, well there are quite an amount of changes. We need tests, I don't want to have any regressions.

**Comment by JohnPittman** [comment]
Also need to add 'defer' option to script tags where a script can be 'async' or 'defer'.  both are very relevant.

**Comment by JohnPittman** [comment]
I am going to end up writing my own WebIndexPlugin for a much robust usage. Thanks anyway.

**Comment by nchanged** [comment]
Feel free to share it with us! 😃

**Comment by JohnPittman** [comment]
Version 1 that should solve 95% of needs:

https://github.com/chickendinosaur/fuse-box-web-index-plugin

**Comment by chickendinosaur** [comment]
This is my main account so adding comment to chain.

**Pull request closed without merging**
