### PR TITLE
docs/css-modules

### PR DESCRIPTION
**Pull request by Aktof**
Adds notes about the following in respect to CSSModules plugin:
- installation
- usage
- options
- development and production

### CODE REVIEW

**Comment by nchanged** [comment]
Awesome! Thanks!

**Comment by GGAlanSmithee** [comment]
Sorry for hijacking this, but it seems like a reasonable place to ask;

Using the https://github.com/fuse-box/react-example, I followed the instructions introduced in this PR to add `css-modules` support. Using `useDefault: false`, I can confirm that the generated classnames are applied to the elements, but the CSS is not being added in the `head` of the page. I can confirm that it works as expected when not using modules.

Are there any additional steps needed to make `css-modules` work? Thanks.

**Comment by nchanged** [comment]
@GGAlanSmithee hi, the last plugin the chain should be `CSSPlugin` it won't be injected otherwise.

**Comment by GGAlanSmithee** [comment]
@nchanged yes, that is how I have it setup;

```javascript
const {FuseBox, CSSModules, CSSPlugin, BabelPlugin} = require("fuse-box")

// FuseBox 2.0 is coming soon!
// http://fuse-box.org:3333/

let fuse = new FuseBox({
    homeDir: "src/",
    sourcemaps: true,
    output: "build/$name.js",
    plugins: [
        CSSModules({useDefault: false}),
        CSSPlugin(),
        BabelPlugin()
    ]
})

fuse.dev({port: 8080})

fuse.bundle("app")
    .watch()
    .hmr()
    .instructions("> index.jsx")

fuse.run()
```

**Comment by nchanged** [comment]
That's wrong, please read the [documentation](http://fuse-box.org/plugins/cssmodules-plugin#usage) more carefully 

```
 plugins: [
        [ CSSModules({useDefault: false}),  CSSPlugin() ],
        BabelPlugin()
 ]
```

**Comment by nchanged** [comment]
And [this](http://fuse-box.org/page/configuration#plugins) section too

**Comment by GGAlanSmithee** [comment]
@nchanged do'h ! missed the nested array. Thanks for the help! :1st_place_medal:

**Pull request merged**
