### PR TITLE
fix: switched from node-sass to sass

### LINKED ISSUE #1836: consider switching to dart sass from node-sass
for several reasons:

1. the dart sass is the primary implementation now and other implementations are lagging behind on latest features support (such as `@use` and new module system)
1. node-sass requires a native binary, which has to be downloaded (if the current environment fits in a limited set of platform/node version/node-sass version combinations of their pre-built binaries) or built locally - that's problematic on windows, docker containers, etc.

### PR DESCRIPTION
**Pull request by jpike88**
fixes #1836

### CODE REVIEW

**Review by charsleysa — APPROVED** [review]
LGTM

**Comment by nchanged** [comment]
@jpike88 that introduces a breaking change. Shall we make it compatible with the other module too?

**Comment by jpike88** [comment]
ill make another pr so it jogs the tests

**Comment by jpike88** [comment]
ok that didn't work. ill run them locally I guess

**Comment by jpike88** [comment]
I didn't have any issues with the upgrade on my own project, what breaking change are you referring to?

Is there a test I can run or something

**Comment by jpike88** [comment]
closing in favour of cleaner pr

**Pull request closed without merging**
