### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by orblazer**
Hello,
I have fix all tests, except CLI teast because i don't know how i can fix this.

Thanks

### CODE REVIEW

**Comment by nchanged** [comment]
so what does this PR do? I didn't get it.

**Comment by orblazer** [comment]
This PR clean imports in test and fix error in some test.
I have disable CLI test because the code is rewrited is probably not ended.

**Comment by nchanged** [comment]
I removed that test (we are going to a new CLI mode very soon)
let's try again

**Comment by nchanged** [comment]
Closing this one, too many conflicts and the tests are failing

**Pull request closed without merging**
