### PR TITLE
Markdown plugin

### PR DESCRIPTION
**Pull request by vtabary**
A proposal based on the HTMLPlugin, to :
* support markdown files
* transform markdown files to HTML files

All of this is using marked library https://github.com/chjj/marked

The default marked options are the same than : https://github.com/peerigon/markdown-loader

### CODE REVIEW

**Comment by nchanged** [comment]
Good stuff! Awesome! Please check the review

**Comment by vtabary** [comment]
Sorry, but I'm not really familiar with appveyor. 

After digging, the project doesn't have any appveyor.yml file. I think that's why it's failing. Any tips ?

**Comment by nchanged** [comment]
No worries I will fix it tomorrow (I have not set it up properly yet)

**Comment by nchanged** [comment]
@vtabary did you manage to take a look at my review?

**Comment by vtabary** [comment]
Sorry, but I can't see any review nor comments :/

**Comment by nchanged** [comment]
What about now?

**Comment by vtabary** [comment]
Now it's ok.

I will fix that, thanks for the review.

**Pull request merged**
