### PR TITLE
SASS indent syntax support

### PR DESCRIPTION
**Pull request by iceekey**

### CODE REVIEW

**Comment by iceekey** [comment]
Althrough CSSPlugin test fails I think it's not because of my changes. I did nothing to CSSPlugin. This changes works fine on my PC.

Maybe it fails because project on half way trough?

**Comment by nchanged** [comment]
This `indentedSyntax: true` might have messed it up. Maybe we don't hardcode it and let user decide?

**Comment by iceekey** [comment]
@nchanged then it should be mentioned in documentation. because without it `.sass` files can't be parsed.
`indentedSyntax: true` still allows to parse `.scss` files.

Do I need to update docs for SASSPlugin and remove `indentedSyntax: true` ? You decide.

**Comment by nchanged** [comment]
Please, remove `indentedSyntax` let's leave it for the end user to decide.  Documentation - if it's easy for you, please add a few lines on additional extension support ;-) 
And thank you!

**Pull request merged**
