### PR TITLE
feat(sparky): Add regexp support for task names

### PR DESCRIPTION
**Pull request by freehuntx**
- Added RegExp support for task names

Relates to Issue: https://github.com/fuse-box/fuse-box/issues/1949

### CODE REVIEW

**Review by charsleysa — CHANGES_REQUESTED** [review]
Please limit the PR to just the necessary changes. Don't include the format fixes in this PR.

**Comment by freehuntx** [comment]
Fixed. Can you take a look again?

**Review by nchanged — APPROVED** [review]
👍 looks good!

**Review by charsleysa — APPROVED** [review]
LGTM

**Pull request merged**
