### PR TITLE
move CSS insertion from top of head tag to the bottom

### PR DESCRIPTION
**Pull request by wrench7**
Attends to https://github.com/fuse-box/fuse-box/issues/1444

### CODE REVIEW

**Comment by nchanged** [comment]
Something is off with the tests ;(

**Comment by wrench7** [comment]
Are you on a Mac? I've just run the tests on a PC and getting the following error (which appears to be completely unrelated to the failure I see in the link above):

>C:\Projects\_experiments\fuse-box\.fusebox\tests\1549029640142\test.js:29266
            throw new Exception_1.Exception('Expected ${this.obj} to have ${target}');
            ^
Error: Expected C:\Projects\_experiments\fuse-box\.fusebox\virtual-files\1549029671075\qwerty.js to have /qwerty.js
    at ShouldInstance.findString (C:\Projects\_experiments\fuse-box\.fusebox\tests\1549029640142\test.js:29266:19)
    at env.browser.window (C:\Projects\_experiments\fuse-box\.fusebox\tests\1549029640142\test.js:21779:55)
    at Object.done (C:\Projects\_experiments\fuse-box\.fusebox\tests\1549029640142\test.js:14169:36)
    at process.nextTick (C:\Projects\_experiments\fuse-box\node_modules\jsdom\lib\jsdom.js:325:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by nchanged** [comment]
I need to resolve these tests... They fail from time to time. Are you rebased on master btw?

**Comment by wrench7** [comment]
Yep, I pulled down master before making my branch.

**Pull request merged**
