### PR TITLE
Node.js internal packages should be handled

### PR DESCRIPTION
**Pull request by adrenalin**
This is a patch that allows using libraries that use e.g. zlib on server side, but work without on browsers. There is a bunch of node.js internal packages that may depend on the system configuration and those should be taken into account automatically instead of using empty return values of the current `assets/lib/*.js`

This solution is not yet full as those packages should be served on server side normally.

Sorry for the whitespace issues, Atom strips the trailing whitespace automatically.

### CODE REVIEW

**Comment by nchanged** [comment]
Thanks for your idea, but I can't merge it. The thing is that it __should__ be bundled. Otherwise, bundle won't work in browser.  Please check this [PR](https://github.com/fuse-box/fuse-box/pull/71)

A simple solution is to add it [here](https://github.com/fuse-box/fuse-box/tree/master/assets/libs) 

JSPM works the same way. __zlib__ was simply added to the list https://github.com/fuse-box/fuse-box/blob/master/assets/libs/zlib/index.js

**Comment by adrenalin** [comment]
This sounds like patching over patching with a lot of redundancy needed to support all the missing packages, but ok, as you wish. E.g. `tty` is currently breaking [debug](https://www.npmjs.com/package/debug) because it "exists" but is broken in the eyes of the package, because it doesn't have any of the required methods after the check for existence has been done.

**Comment by nchanged** [comment]
The issue is a bit different. It bugs up on cache

Cuz this [works](https://github.com/fuse-box/fuse-box/blob/master/src-frontend/FuseBox.ts#L174)

**Comment by nchanged** [comment]
@adrenalin you can try fixing the cache instead. Cuz if a package is not in the asset lib, it will still work.

**Comment by nchanged** [comment]
@adrenalin join gitter, i can explain.

**Pull request closed without merging**
