### PR TITLE
Fuse HMR

### PR DESCRIPTION
**Pull request by basarat**
added `fuse-box/modules/fuse-hmr` :rose:

### CODE REVIEW

**Comment by basarat** [comment]
@nchanged struggling to get this to work in the reflux example: 

image

Which keeps failing


image

I tried `rm -rf .fusebox/ && npm start`

**Comment by basarat** [comment]
Works fine in other places as shown below: 

better

**Comment by basarat** [comment]
Ready to be merged whenever you want :rose: 👍

**Comment by nchanged** [comment]
Awesome! :fire:

**Pull request merged**
