### PR TITLE
Report the new size and time taken for UglifyJS

### PR DESCRIPTION
**Pull request by tyrsius**
This is for #167, but it is not ready. I want to start a discussion.

This is what the report looks like currently
image

Obviously the lack of a label on the second report is one issue. I'm a little confused on how @nchanged wants to organize things. Things seem sort of abstracted around the `context` object, but the `Log` modules on `context` seems pretty specific to logging `ModuleCollection`, and their isn't another logging module. 

* Do you want a new logging module to abstract logging?
* Do you want `cursor` use directly in the `UglifyJSPluginClass`
* ... something else?

### CODE REVIEW

**Comment by nchanged** [comment]
Great, let's improve the logging class. It makes sense IMO, 
We need to add warnings maybe?!

**Comment by tyrsius** [comment]
Warnings for what?

**Comment by nchanged** [comment]
In general. Just saying. Should we change the output a bit, when uglified. 
____
Size: 52kb (minified)
Time: 677ms
___
And why you have 2 of them?

**Comment by tyrsius** [comment]
I think if they were both labeled beforehand, like `Fuse bundle` and `UglifyJSPlugin bundle`, the (minified) part would be unnecessary, and make the bundle report summary consistent.

For two of them, to stop the first one from happening you would have to know that that `UglifyJSPlugin` was going to run. Even if you wanted to check for built in plugins that would change the bundle, which I think might be hard, the fuse bundle report is still useful info.

**Comment by nchanged** [comment]
https://github.com/fuse-box/fuse-box/blob/master/src/Log.ts#L78

Shall we expose this one? Or make it customisable?

**Comment by nchanged** [comment]
That means that the Log should have `context`.

**Comment by tyrsius** [comment]
That's what I did here, check out the changed files. For getting the label, if you want to make `Log` the generic module for that, I think it needs a generic `echo` function

**Comment by tyrsius** [comment]
Current revision with label, no hyphens. Ready to merge if you like it

image

**Comment by nchanged** [comment]
Terrific job! Thanks!

**Pull request merged**
