### PR TITLE
move tests to typescript

### PR DESCRIPTION
**Pull request by basarat**
:rose:

### CODE REVIEW

**Comment by basarat** [comment]
@nchanged once this is merged I will proceed to cleaning up the test directory further :rose: e.g. 

- we don't need to use the built `commonjs` version of the our src 
- a lot of the `done` callbacks can just be replaced with a promise chain (mocha natively supports failing tests on promise failures : https://mochajs.org/#working-with-promises )

As always thanks in advance :heart:

**Comment by nchanged** [comment]
Cool! How does one run just one mocha file?

**Comment by basarat** [comment]
> Cool! How does one run just one mocha file?

`describe.only` :rose:

**Comment by basarat** [comment]
image

**Comment by basarat** [comment]
@nchanged added support for terminal `npm run test:only -- test/something.ts` :rose:

**Comment by nchanged** [comment]
Tests are coming soon -)

**Pull request closed without merging**
