### PR TITLE
Commit Message Validation & Formatting

### PR DESCRIPTION
**Pull request by Shepless**
Feel free to close, but please pull this branch down and have a play to see what you think:

- `npm i`

Then do a git commit. Expected message format is `type(scope): short message`, e.g. `feat(bundler): Made the bundler do something cool`. If it doesnt follow this format then it will error.

Let me know what your thoughts are.

### UPDATE
The latest version of this PR will accept either of the following commit messages as valid:

- `type(scope): short message`
- `type: short message`

### CODE REVIEW

**Comment by Shepless** [comment]
@nchanged as discussed in gitter - I will play with the message format but I will have to do it tomorrow evening.

**Comment by Shepless** [comment]
@nchanged I've updated so the scope is no longer validated and can be omitted. Let me know what you think.

**Comment by Shepless** [comment]
@nchanged @calebboyd you guys get a chance to play with the updated rules?

**Comment by nchanged** [comment]
Can we put example commit messages in the description?

**Comment by Shepless** [comment]
Updated description

**Pull request merged**
