### PR TITLE
[wip] extract part of fluent-api from flipbox

### PR DESCRIPTION
**Pull request by aretecode**

### CODE REVIEW

**Comment by nchanged** [comment]
Cool! But but why it's in a text file? )

**Comment by aretecode** [comment]
https://github.com/fuse-box/fuse-box/issues/291

**Comment by leon-andria** [comment]
Can we amend before merged?

**Comment by aretecode** [comment]
@leon-andria @nchanged where should file go? how should it be exposed?

**Comment by leon-andria** [comment]
The fluent API should be independent so it goals is abstract the parsed syntax. 
This means that the api will return at the end the parsed arithmetic string. We need to take benefit of the current implement that is already well tested.
So the bundle should accept in parameters the arithmetic parsed object rather than just a string.
This will keep consistency of the current exposed bundle method.
For the fluent api, it may like below:
BundleExpression.startsWith('entry.ts', withDeps:boolean=false)
.include(['**/*.html'], withDeps:boolean=false)
.exclude(['moment'])
.packAs ('fuse-magic')

Does this make sense and unify the existing implementation?

**Comment by devmondo** [comment]
i think we should have `exclude` and `excludeDeps`

**Comment by aretecode** [comment]
this still doesn't answer the question, where should this file go? how is it exposed? fsbx.BundleExpression?

**Comment by leon-andria** [comment]
I think its good to put it under arithmetic folder under bundlerExpression.ts file. And the final result returns the PropParser object.
Overload methods bundle and initateBundle with typed PropParser type under https://github.com/fuse-box/fuse-box/blob/master/src/core/FuseBox.ts

**Pull request closed without merging**
