### PR TITLE
feat: add language target to control transpilation level

### PR DESCRIPTION
**Pull request by calebboyd**
Here is my approach, let me know what you think 

With this we can probably detect all sorts of language features and do the appropriate transpilation

I went with your suggestion and target now accepts a language target like: `target: 'browser@esnext'`

### CODE REVIEW

**Comment by nchanged** [comment]
Terrific!
One suggestion, if you can add a traversal plugin here

https://github.com/fuse-box/fuse-box/blob/9d0ddd9509973e8bcb61a866efae816ae804b993/src/analysis/FileAnalysis.ts#L20

It would make sense to have a place where we could define levels automatically.

https://github.com/fuse-box/fuse-box/blob/9d0ddd9509973e8bcb61a866efae816ae804b993/src/analysis/FileAnalysis.ts#L149-L154

And I think we might have a buggy situation over here:

https://github.com/fuse-box/fuse-box/blob/9d0ddd9509973e8bcb61a866efae816ae804b993/src/analysis/FileAnalysis.ts#L158-L160

As `this.ast` is not overloaded

It is set over here for instance.

https://github.com/fuse-box/fuse-box/blob/9d0ddd9509973e8bcb61a866efae816ae804b993/src/analysis/plugins/ImportDeclaration.ts#L112-L121

To avoid that, we might need to parse the code again and set the correct AST


I am not sure, but I think we need to regenerate the code before transpiling it, IF `requiresRegenaration` is set

https://github.com/fuse-box/fuse-box/blob/9d0ddd9509973e8bcb61a866efae816ae804b993/src/analysis/plugins/ImportDeclaration.ts#L66

**Comment by calebboyd** [comment]
Can you elaborate on what you mean by 

>It would make sense to have a place where we could define levels automatically.

**Comment by calebboyd** [comment]
@nchanged I added https://github.com/fuse-box/fuse-box/pull/793/commits/a07b7f1d769d3a71f209a90b6321a1a163376e15

**Comment by nchanged** [comment]
Awesome, I would like to push one commit, could you give me an access? 
Of course you can fix it yourself

```
if (this.requiresRegeneration) {
              this.file.contents = this.file.context.generateCode(this.ast);
          }
```

This will be useless if `requiresTranspilation` is set and all aliases will be gone...

**Comment by calebboyd** [comment]
Not sure I fully understand -- Added access https://github.com/calebboyd/fuse-box/invitations

**Pull request merged**
