### PR TITLE
update postcss dependencies

### PR DESCRIPTION
**Pull request by vegarringdal**
update postcss dependencies

Really want newest for tailwindcss

I dont know if I break anything atm, will try and install this branch in my project later today/tomorrow
Wait with merging unless you know it wont break anything

### CODE REVIEW

**Comment by vegarringdal** [comment]
@nchanged 
I dont think it will break anything
Test are working after I fixed the type errors

I tried postcss in fusebox by manually setting v8 in the package-lock.json in one of my project under fusebox.
It worked when I did this (did not before, tailwindcss complained I needed to update)

**Comment by vegarringdal** [comment]
Would it be possible to have it under a own tag and try out some different apps?

`^4.0.0-postcss.1` to try it a bit more before merging ?

**Review by charsleysa — APPROVED** [review]
LGTM

**Comment by vegarringdal** [comment]
Did try out tailwindcss tody by manually settign up the postcss in package lock.
Looks to be working fine when I enable purge in the postcss tailwind plugin

**Review by nchanged — APPROVED** [review]
👍

**Pull request merged**
