### PR TITLE
docs: runtimeBundleMapping

### PR DESCRIPTION
**Pull request by DitlevHB**
Senpai @nchanged, I'm sorry for the delay :snail:

### CODE REVIEW

**Comment by DitlevHB** [comment]
I don't know why all the old commits from May is in this pull request :S 
Although it should be fine to merge, right?

**Comment by nchanged** [comment]
@DitlevHB there are some conflicts. Could you take a look?

**Comment by DitlevHB** [comment]
@nchanged, could you pinpoint where the conflicts are? It says all checks have passed.

**Comment by nchanged** [comment]
@DitlevHB probably some glitch ;-) all good, I will merge it now! thanks!

**Comment by DitlevHB** [comment]
All right, great! 👍

**Pull request merged**
