### PR TITLE
Now dist-commonjs sourcemaps are generated 

### PR DESCRIPTION
**Pull request by andrew-w-ross**
Looks like the original intention of dist-commonjs was to produce source maps to help with debugging. This pull request implements that.

### CODE REVIEW

**Comment by nchanged** [comment]
Thanks, but there are changes all over the place. Could you not change the formatting please?

**Comment by andrew-w-ross** [comment]
Sure, mind sending me an editor config or just telling me what your indentation settings are?

**Comment by nchanged** [comment]
```
  "editor.tabSize": 4,
 "editor.renderWhitespace": "none",
  "editor.wordWrap": "off",
```
Pretty much default with VsCode

**Comment by nchanged** [comment]
Right ;-) and what are the actual changes?

**Comment by andrew-w-ross** [comment]
It looks like the intention for `dist-commonjs` was to [generate sourcemaps](https://github.com/fuse-box/fuse-box/blob/master/gulpfile.js#L118). With this pr the sourcemaps actually get generated.

**Pull request merged**
