### PR TITLE
typedoc implementation

### PR DESCRIPTION
**Pull request by paxperscientiam**
Hello, this is rough. The docs seemed to be built, but I have no idea how to audit them. 

I am unsure how to contend with this error: `Error: Cannot write file '/Users/ramos/repos/fuse-box/src/main/__tests__/cases/projects/src1/index.js' because it would be overwritten by multiple input files.`

### CODE REVIEW

**Comment by nchanged** [comment]
that's cool but we need to select the files we want to document, there is too much noise.

**Comment by paxperscientiam** [comment]
OK, I'll play around.

**Comment by paxperscientiam** [comment]
@nchanged , starting to get hang of it. I was able to hide all private properties and target specific files.

Are we moving in the right direction?

**Comment by paxperscientiam** [comment]
Nuking because I botched something. I'll make a new PR.

**Pull request closed without merging**
