### PR TITLE
Catching typescript transpilation errors

### PR DESCRIPTION
**Pull request by HugoDaniel**
Outputs any errors that occur during transpilation and shows the file where they happened.

Did not test this, just edited the file here directly on github.

### CODE REVIEW

**Comment by mishengqiang** [comment]
no work

**Comment by nchanged** [comment]
It hasn’t been released

**Comment by mishengqiang** [comment]
dbb2881e-b64d-45ba-b9ee-9352b8b1dd40

**Comment by nchanged** [comment]
@RPDeshaies no it's not ;-)

**Pull request merged**
