### PR TITLE
proc.require() doc

### PR DESCRIPTION
**Pull request by eddow**
Sorry, I wrote some doc only afterward.

I don't know why Git says  src/FuseProcess.ts was modified again - if needed, just c/p the help-text and "refuse" this PR.

Please, do not hesitate to rephrase, reformat, etc.

### CODE REVIEW

**Comment by nchanged** [comment]
Cool, thanks i will merge it soon, after editing a bit =)

**Comment by eddow** [comment]
Indeed, after I changed as we need the module's FuseBox export to access the "files" from the bundle. I would still wait for the resolution of the export stuff before finalizing the arguments - I have the impression it would change a lot.

Here, I changed also the callback given to `require` for it not to be a function but an options object (with the callback) to let expansions possible

**Comment by nchanged** [comment]
There are some conflicts.

**Comment by eddow** [comment]
Replaced by https://github.com/fuse-box/fuse-box/pull/546

**Pull request closed without merging**
