### PR TITLE
Fix VuePlugin

### PR DESCRIPTION
**Pull request by Sirikon**
As said in Issue #125 on [this comment](https://github.com/fuse-box/fuse-box/issues/125#issuecomment-298455538)

### CODE REVIEW

**Comment by nchanged** [comment]
I kind of didn't get how would one render a Vue component? ;-)

**Comment by Sirikon** [comment]
Hm.. sorry? I don't understand your question... do you mean why does it work using just _p ?

**Comment by nchanged** [comment]
I mean, you have removed the `View` instance. What does it export then? just an object? Can you give an example on how would you use the plugin?

**Comment by Sirikon** [comment]
When using Vue components all you need to give to Vue to render the component is a plain javascript object with, at least, a render method or template property.

So, in this case with this two files:

```js
// index.ts
import * as Vue from 'vue/dist/vue.js'
import * as App from './components/App.vue'

new Vue({
    el: '#app',
    render: h => h(App)
})
```

```html
<!-- components/App.vue -->
<template>
    <div>
        <p>{{ msg }}</p>
        <input type="text" v-model="msg" />
    </div>
</template>

<script>

    export default {
        name: 'app',
        data () {
            return {
                msg: 'Welcome to Your Vue.js App'
            }
        }
    }

</script>
```

This will work because index.ts creates a new Vue instance, which will use the `h` method inside `render` method, here the `h` method is `createElement` from Vue, which can take just a plain javascript object.

**Comment by Sirikon** [comment]
@nchanged Just made a Github repo with a project that will work once this PR is merged: https://github.com/Sirikon/fuse-box-vue-example

**Comment by nchanged** [comment]
Right, I see, so you wouldn't want to export the entire view? Instead just a template?

**Comment by Sirikon** [comment]
@nchanged Check the `<script>` tag content in `components/App.vue`, it just exports that, a plain javascript object. If the developer using this wants to export an actual Vue instance, can just export it instead of the plain JS object.

This is also, if I'm not wrong, the default behaviour in the official tools for webpack.

**Comment by nchanged** [comment]
@Sirikon ok, it's just I know so little about Vue. You think you could write some docs on it?

**Comment by Sirikon** [comment]
@nchanged Sure! :) will write about it and make another PR

**Comment by nchanged** [comment]
Thanks =)

**Pull request merged**
