### PR TITLE
#904 allow `require('config')` to load json

### PR DESCRIPTION
**Pull request by nalbion**

### CODE REVIEW

**Comment by nalbion** [comment]
I'll admit, it's a bit ugly...

`ExtensionOverrides.setOverrideFileInfo()` returns early if for files in `node_modules`, and it also does not update `file.relativePath`, so the JSON plugin would not fire anyway.

Because this is a language feature, this should all work out-of-the-box without having to explicitly set `extensionOverrides: ['.json']`

**Comment by nchanged** [comment]
What's the actual purpose of it?

**Comment by nalbion** [comment]
@nchanged I'm working (trying to) with `googleapi`. Their code includes 

    var config = require('./some-config-file');

Fusebox currently tries to load `some-config-file.js`, but it needs to load `some-config-file.json`

**Comment by nalbion** [comment]
@nchanged this should resolve #904

**Comment by nchanged** [comment]
Oh I see, In this case we should fix

**Comment by nchanged** [comment]
@nalbion 
How about aliases?

```
alias : {
  "some-config-file" : "some-config-file.json" 
}
```
That should solve your particular issue. Of course, we need to fix it on FuseBox level, but that would  require QuantumPlugin fix as well

**Comment by Kompwu** [comment]
@nchanged Can we close it now?

**Comment by nchanged** [comment]
Closing this for now.

**Pull request closed without merging**
