### PR TITLE
chore: "opn" is deprecated, it's renamed to "open"

### PR DESCRIPTION
**Pull request by 3cp**

### CODE REVIEW

**Comment by nchanged** [comment]
@3cp please note, that `v4` branch will be merged soon. If you want, you could add this functionality right [here](https://github.com/fuse-box/fuse-box/blob/v4/src/dev-server/devServer.ts)

**Comment by 3cp** [comment]
I am lost, I didn't see opn there. Is that "open browser" feature removed from v4 (at least for now)?

**Comment by nchanged** [comment]
@3cp it wasn't removed ;-) It's not implemented. Since `v4` is a total re-write with immense speed boost and improvements.

**Comment by nchanged** [comment]
Anyway, I encourage you to try https://github.com/fuse-box/react-example/tree/v4

**Comment by 3cp** [comment]
I see :)
I'll close this one. I think that's easy for you to add the feature back to v4.

**Comment by nchanged** [comment]
@3cp `fuse-box@4.0.0-alpha.54` you can try it here. 

Here are the [options](https://github.com/fuse-box/fuse-box/blob/v4/src/dev-server/devServerProps.ts#L24-L35)

```
devServer : { open : true }
```

**Comment by 3cp** [comment]
thx!

**Pull request closed without merging**
